version: '3.1'

services:

  db:
    image: postgres
    restart: always
    container_name: dev_camp_db
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - ./tmp/db_data:/var/lib/postgresql/data
    ports:
    - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  app:
    image: node:14
    working_dir: /src
    volumes:
    - ./:/src
    ports:
      - 4000:4000
    command: npm run dev
