version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  app:
    image: node:14
    working_dir: /src
    volumes:
    - ./:/src
    ports:
      - 3030:3030
    command: npm run dev
